# nixpacks.toml

[phases.setup]
nixPkgs = ['nodejs', 'python3', 'cowsay']

[phases.build]
cmds = [
  "poetry install",
  "cd frontend && npm install && npm run build"
]

[start]
cmd = "python manage.py runserver"
